global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['localhost:9090'] 

- job_name: QoS-Metrics # Nome do job, ou seja, o nome do serviço que o Prometheus vai monitorar.
  scrape_interval: 15s # Intervalo de coleta dos dados, ou seja, a cada 15 segundos o Prometheus vai até o alvo monitorado coletar as métricas, o padrão é 1 minuto.
  scrape_timeout: 10s # Intervalos para o Prometheus aguardar o alvo monitorado responder antes de considerar que o alvo está indisponível, o padrão é 10 segundos.
  metrics_path: /metrics # path em que o prometheus vai procurar 10.0.0.2:5000/metrics
  static_configs:
    - targets:
      - 10.0.0.2:5000 # Endereço do alvo monitorado, ou seja, o endereço do serviço que o Prometheus vai monitorar.